# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    # Route pour l'insertion de l'image de Profil
    participant_image_directory: '%kernel.project_dir%/public/img/user/profilePicture'

    # Route pour l'insertion de l'image du Lieu
    lieu_ImageUpload_directory: '%kernel.project_dir%/public/img/lieu/lieuUserUploadPicture'

    # Route pour l'insertion de l'image du Site
    sortie_ImageUpload_directory: '%kernel.project_dir%/public/img/sortie/sortieUserUploadPicture'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
